"""This is a record of all of my physical music, as of 06/22/2024
Myriah Hodgson :) """

r = 'Rock'
p = 'Pop'
f = 'Folk'
e = 'Electronic'
d = 'Dance'

cds = [['Doggy Style', 'Snoop Doggy Dog', 1993, ['Hip Hop', 'Gangsta Rap', 'G Funk']],
    ['Walk On', 'Boston', 1994, [r]],
    ['Room On Fire', 'The Strokes', 2003, [r, 'Indie']],
    ['Wish You Were Here', 'Pink Floyd', 1975, [r]],
    ['Wish', 'The Cure', 1992, ['Indie', p]],
    ['Day & Age', 'The Killers', 2008, [r, p]],
    ['Boyz II Men', 'Boyz II Men', 1991, ['Hip Hop']],
    ['Chicago Greatest Hits', 'Chicago', 1989, [r]],
    ['4 Way Street', 'Crosby, Stills, Nash & Young', 1971, [r, f]],
    ['Like A Prayer', 'Madonna', 1989, ['Indie', p, r]],
    ['Steve Miller Band Greatest Hits', 'Steve Miller Band', 1978, [p, r]],
    ['Sigh No More', 'Mumford & Sons', 2009, [f, r, 'Indie']],
    ['Hell Freezes Over', 'Eagles', 1994, [r]], 
    ['Sheryl Crow', 'Sheryl Crow', 1996, [r, p, 'Country', 'Blues']], 
    ['Gloria Estefan Greatest Hits', 'Gloria Estefan', 1992, [p, 'Dance']],
    ['Whitney Houston', 'Whitney Houston', 1985, [p]],
    ['Eagles', 'Eagles', 1972, [r, 'Country']],
    ['Tapestry', 'Carole King', 1971, [r, p]],
    ['All The Right Reasons', 'Nickelback', 2005, [r, 'Indie']],
    ['Louder Than Bombs', 'The Smiths', 1987, [r, 'Indie']],
    ['Bad Co', 'Bad Co', 1974, [r]],
    ['Mixed Up', 'The Cure', 1990, ['Indie', 'Dance']],
    ['Head Over Heels', 'Paula Abdul', 1995, [p]],
    ['Tango In The Night', 'Fleetwood Mac', 1987, ['Indie', p, r]],
    ['Loveless', 'My Bloody Valentine', 1991, ['Indie', 'Shoegaze']],
    ['Dixie Chicks', 'Dixie Chicks', 1997, ['Country']],
    ['London Calling', 'The Clash', 1979, ['Punk', r]],
    ['Blue Bannisters', 'Lana Del Rey', 2021, ['Indie']],
    ['The Who', 'The Who', 2002, ['Indie', r]],
    ['Double Vision', 'Foreigner', 1978, [r]],
    ['Speaking In Tongues', 'Talking Heads', 1983, [r, 'Funk']],
    ['The Police, Live!', 'The Police', 1995, ['Funk', 'Punk', r, p]]]

cassettes = [['Straight Shooter', 'Bad Co', 1975, [r]],
    ['Night Moves', 'Bob Seger', 1976, [r]],
    ['Wide Awake In Dreamland', 'Pat Benatar', 1988, [r]]]

vinyl = [['I Like It When You Sleep, For You Are So Beautiful Yet So Unaware Of It', 'The 1975', 2016, [p, 'Indie']],
    ['Being Funny In A Foreign Language', 'The 1975', 2022, ['Indie', p]],
    ['The 1975 10 Year Anniversary', 'The 1975', 2023, [p, r, 'Indie']],
    ['A Brief Inquiry Into Online Relationships', 'The 1975', 2018, [p, r, 'Indie', 'Dance']],
    ['Four Roses Dance Party', 'The Four Roses Society', 1961, ['Jazz']],
    ['Suite For Flute And Jazz Piano', 'Claude Bolling', 1975, ['Jazz']],
    ['A Taste Of Honey', 'Martin Denny', 1962, ['Jazz']],
    ['Are You Ready!', 'Atlanta Rhythm Section', 1979, ['Blues', r]],
    ['Gold, Vol I', 'Bee Gees', 1976, [r, 'Disco', p]],
    ['Night Moves', 'Bob Seger', 1976, [r]],
    ['When We Were Friends', 'The Backseat Lovers', 2019, [r, 'Indie']],
    ['Desolation Angels', 'Bad Co', 1979, [r]],
    ['Bad Co', 'Bad Co', 1974, [r]], 
    ['Cheap Trick At Budokan', 'Cheap Trick', 1978, [r]],
    ['Heaven Or Las Vegas', 'Cocteau Twins', 1990, [p, 'Indie']],
    ['Kiss Me Kiss Me Kiss Me', 'The Cure', 1987, [r, p, 'Indie']],
    ['Candy-O', 'The Cars', 1979, [r, p]],
    ['Tolouse Street', 'The Doobie Brothers', 1972, [r, f]],
    ['Best Of The Doobies', 'The Doobie Brothers', 1976, [r, f]],
    ['Mirror Image', 'Eagles', 1980, [r, 'Country', f]],
    ['Hotel California', 'Eagles', 197, [r, 'Country', f]],
    ['One Of These Nights', 'Eagles', 1975, [r, 'Country', f]],
    ['Tango In The Night', 'Fleetwood Mac', 1987, ['Indie', r, p]],
    ['Rumours', 'Fleetwood Mac', 1977, ['Indie', p, r, f]],
    ['Fleetwood Mac Greatest Hits', 'Fleetwood Mac', 1988, ['Indie', p, r, f]],
    ['Penguin', 'Fleetwood Mac', 1973, ['Blues', p, r, f]],
    ['Foreigner', 'Foreigner', 1977, [r]],
    ['Hozier', 'Hozier', 2014, ['Indie', 'Blues', f]],
    ['Wasteland, Baby', 'Hozier', 2019, ['Indie', p]],
    ['Janis Joplin Greatest Hits', 'Janis Joplin', 1973, [r]],
    ['Winds Of Change', 'Jefferson Starship', 1982, [r, 'Dance']],
    ['Melodrama', 'Lorde', 2017, ['Indie', p]],
    ['Pure Heroine', 'Lorde', 2013, ['Indie', p]],
    ['Solar Power', 'Lorde', 2021, ['Indie', p]],
    ['Norman Fucking Rockwell!', 'Lana Del Rey', 2019, ['Indie', r]],
    ['Icon', 'Lynyrd Skynyrd', 2010, [r]],
    ['Like A Virgin', 'Madonna', 1984, [p, 'Dance']],
    ['Heard It In A Past Life', 'Maggie Rogers', 2019, ['Indie', p]],
    ['Notes From The Archive', 'Maggie Rogers', 2020, [f, 'Indie']],
    ["Don't Forget Me", 'Maggie Rogers', 2024, ['Indie', p, f]],
    ['Babel', 'Mumford & Sons', 2012, [f, r, 'Country', 'Indie']],
    ['The Best Of Nat King Cole', 'Nat King Cole', 1960, ['Jazz']],
    ['Dark Side Of The Moon', 'Pink Floyd', 1973, [r]],
    ['Nine Lives', 'REO Speedwagon', 1979, [r]],
    ['The New Abnormal', 'The Strokes', 2020, ['Indie', r]],
    ['Supremes Greatest Hits', 'Supremes', 1967, ['Soul', p]],
    ['Room On Fire', 'The Strokes', 2003, ['Indie', r]],
    ['The Queen Is Dead', 'The Smiths', 1986, ['Indie', r, p, f]],
    ['Book Of Dreams', 'Steve Miller Band', 1977, [r]],
    ['Fly Like An Eagle', 'Steve Miller Band', 1976, [r]],
    ['Live In Concert, The 24 Karat Gold Tour', 'Stevie Nicks', 2020, [r]],
    ['Dig Me Out', 'Sleater Kinney', 1997, ['Punk', r]],
    ['Evermore', 'Taylor Swift', 2020, ['Indie', p]],
    ['Wings Greatest', 'Wings', 1978, [r]],
    ['Led Zeppelin IV', 'Led Zeppelin', 1971, [r, 'Blues']],
    ['Bella Donna', 'Stevie Nicks', 1981, [r, f]]]

